package com.mycompany.CardGameEngineBlackjack.Domain.Enum;

enum StatoPartita { INIZIALIZZAZIONE, IN_CORSO, TERMINATA }
enum Turno { GIOCATORE, DEALER }
enum EsitoPartita { VITTORIA_GIOCATORE, VITTORIA_DEALER, PAREGGIO, IN_ATTESA }
enum StatoMano { IN_GIOCO, STATA, SBALLATA, BLACKJACK }
enum StatoMazzo { PRONTO, DA_MESCOLARE, ESAURITO }
enum Seme { CUORI, QUADRI, FIORI, PICCHE }
enum Rango { ASSO, DUE, TRE, QUATTRO, CINQUE, SEI, SETTE, OTTO, NOVE, DIECI, JACK, REGINA, RE }
enum TaglioFiche { UNO, CINQUE, DIECI, VENTICINQUE, CENTO, CINQUECENTO }
